import { Product, Category, Collection, Coupon, LookbookItem, ShippingZone, StoreSettings, AdminUser, Review } from '@/types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'RADIICATO',
  tagline: 'Independent streetwear engineered in Nairobi for those who refuse to blend in.',
  contactEmail: 'concierge@radiicato.co.ke',
  contactPhone: '+254 712 904 883',
  currency: 'KES',
  country: 'Kenya',
  address: 'Studio 04, The Alchemist Yard, Parklands Road, Nairobi, Kenya',
  mpesaPaybill: '729831',
  mpesaAccountName: 'RADIICATO APPAREL LTD',
  mpesaPasskey: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919',
  paystackPublicKey: 'pk_test_radiicato_9837198273891723',
  enableMpesa: true,
  enablePaystack: true,
  socialInstagram: 'https://instagram.com/radiicato',
  socialTiktok: 'https://tiktok.com/@radiicato',
  socialTwitter: 'https://twitter.com/radiicato',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-tees',
    name: 'T-Shirts',
    slug: 't-shirts',
    description: 'Heavyweight 280 GSM oversized and boxy streetwear tees with 3D chrome emblems, underground graffiti, and custom album tribute graphics.',
    imageUrl: '/images/products/broken-record-front.jpg',
    status: 'active',
    displayOrder: 1,
    seoTitle: 'Radiicato Oversized Graphic T-Shirts | Premium Kenyan Streetwear',
    seoDescription: 'Shop heavyweight 280 GSM Kenyan streetwear tees: Broken Record White Tee and We Are Who We Are Black Tee.',
  },
  {
    id: 'cat-caps',
    name: 'Skull Caps & Headwear',
    slug: 'caps',
    description: 'Heavyweight double-layered knit skull caps with 3D signature script insignia. Available now in Onyx Black, Slate Grey, and Midnight Camo.',
    imageUrl: '/images/products/radiicato-skull-cap-black.jpg',
    status: 'active',
    displayOrder: 2,
    seoTitle: 'Radiicato Signature Heavyweight Skull Caps | Now Live Nairobi',
    seoDescription: 'Heavyweight double-layered streetwear skull caps. Engineered for Nairobi nights in Onyx Black, Slate Grey, and Midnight Blue Camo. KES 500.',
  },
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-broken-record',
    name: 'BROKEN RECORD',
    slug: 'broken-record',
    description: 'The official White Atelier Capsule. Cut in an architectural oversized silhouette from heavyweight 280 GSM combed cotton. Features the signature 3D chrome metallic oval logo badge on the front chest and the iconic shattered MF DOOM vinyl record tribute on the reverse.',
    coverImage: '/images/products/broken-record-front.jpg',
    bannerImage: '/images/broken-record.jpg',
    status: 'live',
    isScheduled: false,
    displayOrder: 1,
    productIds: ['prod-broken-record-tee'],
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'col-we-are-who-we-are',
    name: 'WE ARE WHO WE ARE',
    slug: 'we-are-who-we-are',
    description: 'The official Black Atelier Capsule. Rebellious Nairobi underground streetwear cut from washed luxury cotton. Features the signature Radiicato mascot graffiti on the chest and the iconic "W W W R R" (We Are Who We Are) collage on the back.',
    coverImage: '/images/products/we-are-who-we-are-front.jpg',
    bannerImage: '/images/we-are-who-we-are.jpg',
    status: 'live',
    isScheduled: false,
    displayOrder: 2,
    productIds: ['prod-we-are-who-we-are-tee'],
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'col-skull-caps',
    name: 'SKULL CAPS',
    slug: 'skull-caps',
    description: 'Heavyweight double-layered skull caps engineered for chilly Nairobi nights. Finished with the signature 3D Radiicato script insignia on the folded cuff. Available now in Onyx Black, Slate Grey, and Midnight Blue Camo.',
    coverImage: '/images/products/radiicato-skull-cap-black.jpg',
    bannerImage: '/images/products/radiicato-skull-cap-camo.jpg',
    status: 'live',
    isScheduled: false,
    displayOrder: 3,
    productIds: ['prod-skull-cap-teaser'],
    createdAt: '2026-03-05T00:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-broken-record-tee',
    name: 'Radiicato "Broken Record" Heavyweight Tee',
    slug: 'broken-record-heavyweight-tee',
    shortDescription: 'Heavyweight 280 GSM crisp white streetwear tee with official 3D chrome metallic oval badge front and shattered MF DOOM vinyl record tracklist back.',
    description: `Engineered in Nairobi for young fashion-conscious Kenyans and creatives who refuse to blend in.

The "Broken Record" tee is cut from heavyweight 280 GSM combed cotton in an architectural relaxed streetwear silhouette with dropped shoulders and double-needle collar ribbing.

The chest features the official 3D chrome metallic Radiicato badge with military olive interior, while the reverse commands attention with an intricate shattered vinyl record graphic paying tribute to underground music culture with engraved track titles (Accordion, Rapp Snitch Knishes, All Caps, Doomsday, Meat Grinder, Figaro) and an MF DOOM chrome mask center medallion. Hand-finished in our Nairobi atelier.`,
    price: 1000,
    costPrice: 450,
    sku: 'RAD-TEE-BR-WHT',
    categoryId: 'cat-tees',
    collectionId: 'col-broken-record',
    brand: 'RADIICATO',
    material: '100% Heavyweight Combed Organic Cotton (280 GSM)',
    fit: 'Relaxed Oversized Drape. True to size for intended streetwear silhouette, or size down for standard fit.',
    careInstructions: 'Machine wash cold inside out with similar colors. Do not iron directly on metallic graphic prints. Lay flat to dry.',
    gender: 'unisex',
    tags: ['broken record', 'white', 'oversized', 'chrome', 'mf doom', 'kenya', 'graphic tee', 'bestseller'],
    status: 'active',
    isFeatured: true,
    isLimitedDrop: false,
    images: [
      {
        id: 'img-br-1',
        productId: 'prod-broken-record-tee',
        url: '/images/products/broken-record-front.jpg',
        altText: 'Radiicato Broken Record Heavyweight Tee Front with 3D Chrome Oval Logo',
        isPrimary: true,
        isHover: false,
        displayOrder: 1,
      },
      {
        id: 'img-br-2',
        productId: 'prod-broken-record-tee',
        url: '/images/products/broken-record-back.jpg',
        altText: 'Radiicato Broken Record Back View with Shattered MF DOOM Vinyl Record',
        isPrimary: false,
        isHover: true,
        displayOrder: 2,
      },
      {
        id: 'img-br-3',
        productId: 'prod-broken-record-tee',
        url: '/images/products/broken-record-full.jpg',
        altText: 'Radiicato Broken Record Front and Back Editorial Flat Lay',
        isPrimary: false,
        isHover: false,
        displayOrder: 3,
      },
      {
        id: 'img-br-4',
        productId: 'prod-broken-record-tee',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
        altText: 'Editorial Street Campaign Model Shot in Nairobi',
        isPrimary: false,
        isHover: false,
        displayOrder: 4,
      },
    ],
    variants: [
      { id: 'v-br-wht-xs', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'XS', sku: 'RAD-TEE-BR-WHT-XS', stockQuantity: 6, lowStockThreshold: 2 },
      { id: 'v-br-wht-s', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'S', sku: 'RAD-TEE-BR-WHT-S', stockQuantity: 12, lowStockThreshold: 3 },
      { id: 'v-br-wht-m', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'M', sku: 'RAD-TEE-BR-WHT-M', stockQuantity: 18, lowStockThreshold: 4 },
      { id: 'v-br-wht-l', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'L', sku: 'RAD-TEE-BR-WHT-L', stockQuantity: 15, lowStockThreshold: 4 },
      { id: 'v-br-wht-xl', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'XL', sku: 'RAD-TEE-BR-WHT-XL', stockQuantity: 5, lowStockThreshold: 3 },
      { id: 'v-br-wht-xxl', productId: 'prod-broken-record-tee', colorName: 'Crisp Atelier White', colorHex: '#FFFFFF', size: 'XXL', sku: 'RAD-TEE-BR-WHT-XXL', stockQuantity: 3, lowStockThreshold: 2 },
    ],
    seoTitle: 'Radiicato "Broken Record" White Heavyweight Streetwear Tee (KES 1,000)',
    seoDescription: 'Shop the official Radiicato Broken Record tee for KES 1,000. Heavyweight 280 GSM combed cotton with 3D chrome metallic logo and shattered MF DOOM vinyl reverse.',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-08T12:00:00Z',
  },
  {
    id: 'prod-we-are-who-we-are-tee',
    name: 'Radiicato "We Are Who We Are" Boxy Tee',
    slug: 'we-are-who-we-are-boxy-tee',
    shortDescription: 'Heavyweight 280 GSM washed obsidian black tee with Radiicato graffiti character mascot front and iconic "W W W R R" paper collage back.',
    description: `An unapologetic non-conformist statement for Kenyan streetwear culture.

The "We Are Who We Are" tee is cut in a boxy dropped-shoulder silhouette from premium washed vintage black cotton (280 GSM).

The front features our underground character mascot wearing a green bucket hat and sunglasses with puff graffiti Radiicato typography, while the back features the iconic "W W W R R" ("We Are Who We Are") distressed color block paper cutout collage. Engineered in Nairobi to represent the raw creative energy of Kenyan youth.`,
    price: 800,
    costPrice: 350,
    sku: 'RAD-TEE-WAW-BLK',
    categoryId: 'cat-tees',
    collectionId: 'col-we-are-who-we-are',
    brand: 'RADIICATO',
    material: '100% Vintage Washed Cotton (280 GSM)',
    fit: 'Boxy Drop-Shoulder Fit. Substantial drape with structured neckline.',
    careInstructions: 'Wash cold inside out. Gentle cycle. Do not bleach. Air dry.',
    gender: 'unisex',
    tags: ['we are who we are', 'black', 'boxy', 'graffiti', 'mascot', 'kenya', 'underground', 'bestseller'],
    status: 'active',
    isFeatured: true,
    isLimitedDrop: false,
    images: [
      {
        id: 'img-waw-1',
        productId: 'prod-we-are-who-we-are-tee',
        url: '/images/products/we-are-who-we-are-front.jpg',
        altText: 'Radiicato We Are Who We Are Boxy Tee Front with Mascot and Graffiti',
        isPrimary: true,
        isHover: false,
        displayOrder: 1,
      },
      {
        id: 'img-waw-2',
        productId: 'prod-we-are-who-we-are-tee',
        url: '/images/products/we-are-who-we-are-back.jpg',
        altText: 'Radiicato We Are Who We Are Back View with WWWRR Cutout Collage',
        isPrimary: false,
        isHover: true,
        displayOrder: 2,
      },
      {
        id: 'img-waw-3',
        productId: 'prod-we-are-who-we-are-tee',
        url: '/images/products/we-are-who-we-are-full.jpg',
        altText: 'Radiicato We Are Who We Are Front and Back Editorial Flat Lay',
        isPrimary: false,
        isHover: false,
        displayOrder: 3,
      },
      {
        id: 'img-waw-4',
        productId: 'prod-we-are-who-we-are-tee',
        url: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000&auto=format&fit=crop',
        altText: 'Editorial Street Culture Model Shot in Nairobi',
        isPrimary: false,
        isHover: false,
        displayOrder: 4,
      },
    ],
    variants: [
      { id: 'v-waw-blk-xs', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'XS', sku: 'RAD-TEE-WAW-BLK-XS', stockQuantity: 5, lowStockThreshold: 2 },
      { id: 'v-waw-blk-s', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'S', sku: 'RAD-TEE-WAW-BLK-S', stockQuantity: 14, lowStockThreshold: 3 },
      { id: 'v-waw-blk-m', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'M', sku: 'RAD-TEE-WAW-BLK-M', stockQuantity: 20, lowStockThreshold: 4 },
      { id: 'v-waw-blk-l', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'L', sku: 'RAD-TEE-WAW-BLK-L', stockQuantity: 16, lowStockThreshold: 4 },
      { id: 'v-waw-blk-xl', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'XL', sku: 'RAD-TEE-WAW-BLK-XL', stockQuantity: 7, lowStockThreshold: 3 },
      { id: 'v-waw-blk-xxl', productId: 'prod-we-are-who-we-are-tee', colorName: 'Washed Obsidian Black', colorHex: '#0A0A0A', size: 'XXL', sku: 'RAD-TEE-WAW-BLK-XXL', stockQuantity: 2, lowStockThreshold: 2 },
    ],
    seoTitle: 'Radiicato "We Are Who We Are" Black Streetwear Tee (KES 800)',
    seoDescription: 'Shop the official Radiicato We Are Who We Are black tee for KES 800. Heavyweight washed cotton with mascot graffiti and WWWRR reverse collage.',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-08T12:00:00Z',
  },
  {
    id: 'prod-skull-cap-teaser',
    name: 'Radiicato Signature Heavyweight Skull Cap',
    slug: 'radiicato-heavyweight-ribbed-knit-skull-cap',
    shortDescription: 'Capsule 03: Heavyweight double-layered knit skull cap featuring the 3D Radiicato script insignia on the cuff. Contoured low-profile silhouette engineered in Nairobi.',
    description: `The Radiicato Signature Skull Cap represents Capsule 03 of the atelier line. 

Engineered specifically for chilly Nairobi evenings, underground DJ sets, and raw urban styling. Crafted with double-layered dense knit for structured warmth and finished with the signature 3D high-density Radiicato script embroidery along the cuff brim.

Available in three distinct colorways:
- Onyx Black (Monochrome Silver/White 3D Logo)
- Slate Grey (Clean Contrast White 3D Logo)
- Midnight Blue Camo (Subdued Multi-Tone Camouflage with Chrome Insignia)

Unisex one-size contoured crown with elastic memory retention.`,
    price: 500,
    costPrice: 200,
    sku: 'RAD-CAP-SKULL-001',
    categoryId: 'cat-caps',
    collectionId: 'col-skull-caps',
    brand: 'RADIICATO',
    material: 'Double-Layered Heavyweight Stretch-Knit Cotton Blend',
    fit: 'Low-Profile Contoured Streetwear Beanie Fit (Unisex One-Size)',
    careInstructions: 'Hand wash cold. Lay flat to dry.',
    gender: 'unisex',
    tags: ['skull cap', 'beanie', 'headwear', 'capsule 03', 'now live', 'black', 'grey', 'camo'],
    status: 'active',
    isFeatured: true,
    isLimitedDrop: true,
    images: [
      {
        id: 'img-sc-black',
        productId: 'prod-skull-cap-teaser',
        url: '/images/products/radiicato-skull-cap-black.jpg',
        altText: 'Radiicato Skull Cap in Onyx Black with White 3D Logo',
        isPrimary: true,
        isHover: false,
        displayOrder: 1,
      },
      {
        id: 'img-sc-grey',
        productId: 'prod-skull-cap-teaser',
        url: '/images/products/radiicato-skull-cap-grey.jpg',
        altText: 'Radiicato Skull Cap in Slate Grey with White 3D Logo',
        isPrimary: false,
        isHover: true,
        displayOrder: 2,
      },
      {
        id: 'img-sc-camo',
        productId: 'prod-skull-cap-teaser',
        url: '/images/products/radiicato-skull-cap-camo.jpg',
        altText: 'Radiicato Skull Cap in Midnight Blue Camo with Chrome Insignia',
        isPrimary: false,
        isHover: false,
        displayOrder: 3,
      },
    ],
    variants: [
      { id: 'v-sc-blk', productId: 'prod-skull-cap-teaser', colorName: 'Onyx Black', colorHex: '#0A0A0A', size: 'ONE SIZE', sku: 'RAD-CAP-SKULL-BLK', stockQuantity: 45, lowStockThreshold: 5 },
      { id: 'v-sc-gry', productId: 'prod-skull-cap-teaser', colorName: 'Slate Grey', colorHex: '#6B7280', size: 'ONE SIZE', sku: 'RAD-CAP-SKULL-GRY', stockQuantity: 35, lowStockThreshold: 5 },
      { id: 'v-sc-cmo', productId: 'prod-skull-cap-teaser', colorName: 'Midnight Blue Camo', colorHex: '#2B3A4A', size: 'ONE SIZE', sku: 'RAD-CAP-SKULL-CMO', stockQuantity: 25, lowStockThreshold: 5 },
    ],
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-12T08:00:00Z',
  },
];

export const INITIAL_LOOKBOOK: LookbookItem[] = [
  {
    id: 'lb-1',
    title: 'KILIMANI ROOFTOP SESSIONS — BROKEN RECORD',
    description: 'Capturing the architectural drape of the Broken Record white tee against the high-rise skyline of Nairobi. Hand-finished 3D chrome metallic emblem catching midday Kenyan sun.',
    imageUrl: '/images/products/broken-record-front.jpg',
    collectionSlug: 'broken-record',
    displayOrder: 1,
  },
  {
    id: 'lb-2',
    title: 'WESTLANDS UNDERGROUND SOUND — WE ARE WHO WE ARE',
    description: 'Shot in an underground recording studio in Westlands, Nairobi. Heavyweight washed black boxy drape commanding presence with the iconic WWWRR paper collage back.',
    imageUrl: '/images/products/we-are-who-we-are-front.jpg',
    collectionSlug: 'we-are-who-we-are',
    displayOrder: 2,
  },
  {
    id: 'lb-3',
    title: 'ALCHEMIST YARD EDITORIAL — MF DOOM VINYL REVERSE',
    description: 'Detailed focus on the shattered metallic vinyl record back print and chrome mask medallion. Nairobi creative youth reclaiming vinyl culture.',
    imageUrl: '/images/products/broken-record-back.jpg',
    collectionSlug: 'broken-record',
    displayOrder: 3,
  },
  {
    id: 'lb-4',
    title: 'NAIROBI NIGHTS EDITORIAL — CAPSULE 03 SKULL CAPS',
    description: 'The newly launched Radiicato Signature Heavyweight Skull Cap in Onyx Black, Slate Grey, and Midnight Blue Camo. Contoured silhouette engineered for the cold Nairobi sets.',
    imageUrl: '/images/products/radiicato-skull-cap-black.jpg',
    collectionSlug: 'skull-caps',
    displayOrder: 4,
  },
  {
    id: 'lb-5',
    title: 'URBAN TACTICAL STUDY — MIDNIGHT CAMO SKULL CAP',
    description: 'Subdued multi-tone blue camouflage skull cap accented with the high-relief metallic script insignia. Nairobi streetwear elevated.',
    imageUrl: '/images/products/radiicato-skull-cap-camo.jpg',
    collectionSlug: 'skull-caps',
    displayOrder: 5,
  },
];

export const INITIAL_SHIPPING_ZONES: ShippingZone[] = [
  {
    id: 'zone-nrb',
    name: 'Nairobi Express Delivery',
    counties: ['Nairobi'],
    standardFee: 350,
    expressFee: 600,
    freeShippingThreshold: 10000,
    estimatedDays: 'Same-day (Order before 2 PM) or Next Day via Rider',
  },
  {
    id: 'zone-kiambu',
    name: 'Kiambu & Greater Nairobi Metro',
    counties: ['Kiambu', 'Machakos', 'Kajiado'],
    standardFee: 450,
    expressFee: 750,
    freeShippingThreshold: 12000,
    estimatedDays: '1 - 2 Business Days',
  },
  {
    id: 'zone-major-towns',
    name: 'Major Kenyan Cities (Mombasa, Kisumu, Nakuru, Eldoret)',
    counties: ['Mombasa', 'Kisumu', 'Nakuru', 'Uasin Gishu', 'Kilifi'],
    standardFee: 650,
    expressFee: 1100,
    freeShippingThreshold: 15000,
    estimatedDays: '2 - 3 Business Days via Fargo Courier / Wells Fargo',
  },
  {
    id: 'zone-rest-ke',
    name: 'Rest of Kenya (All 47 Counties)',
    counties: ['Other Kenya'],
    standardFee: 800,
    expressFee: 1300,
    freeShippingThreshold: 18000,
    estimatedDays: '3 - 4 Business Days',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'FIRSTDROP',
    discountType: 'percentage',
    value: 10,
    minOrder: 3500,
    usageLimit: 500,
    timesUsed: 42,
    isActive: true,
    startDate: '2026-01-01T00:00:00Z',
  },
  {
    id: 'coup-2',
    code: 'NAIROBI500',
    discountType: 'fixed',
    value: 500,
    minOrder: 5000,
    usageLimit: 200,
    timesUsed: 88,
    isActive: true,
    startDate: '2026-01-01T00:00:00Z',
  },
  {
    id: 'coup-3',
    code: 'RADIICATOVIP',
    discountType: 'percentage',
    value: 15,
    minOrder: 8000,
    usageLimit: 100,
    timesUsed: 19,
    isActive: true,
    startDate: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [];

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm-owner-1',
    name: 'Joshua Kigen',
    email: 'joshkigs8@gmail.com',
    role: 'SUPER_ADMIN',
    lastLogin: '2026-09-10T10:00:00Z',
    status: 'active',
  },
];
